version: '3'

services:
  node1:
    image: Erickim777/EthereumCash
    container_name: ethereumcash-node1
    volumes:
      - ../EthereumCashd:/var/lib/turtlecoind/
    networks:
      testnet:
        ipv4_address: 211.39.150.252
  
#  node2:
#    image: Erickim777/EthereumCash
#    container_name: ethereumcash-node2
#    networks:
#      testnet:
#        ipv4_address: 211.39.150.247
  
#  node3:
#    image: Erickim777/EthereumCash
#    container_name: ethereumcash-node3
#    networks:
#      testnet:
#        ipv4_address: 211.39.150.248

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24


